version: '3'

services:
  php:
    container_name: 'php'
    build: ./containers/php
    ports:
      - 9000
      - 8080:80
    volumes:
      - ./containers/php/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/php/nginx/conf.d:/etc/nginx/conf.d
      - ../:/var/www/src
      - ./containers/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    tty: true
    depends_on:
      - localstack
    networks:
      furoshiki:
        aliases:
          - php

  mysql:
    container_name: 'mysql'
    build: ./containers/mysql
    volumes:
      - ./containers/mysql/db:/var/lib/mysql
      - ./containers/mysql/my.cnf:/etc/mysql/my.cnf
      - ./containers/mysql/log:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      DB_NAMES: furoshiki
      MYSQL_DATABASE: furoshiki
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    tty: true
    networks:
      furoshiki:
        aliases:
          - mysql

  localstack:
    container_name: 'localstack'
    image: localstack/localstack
    volumes:
      - ./containers/localstack:/tmp/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_OUTPUT=json
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=secret
      - DATA_DIR=/tmp/localstack/data
    ports:
      - 8000:8080
      - 4567-4578:4567-4578
    networks:
      furoshiki:
        aliases:
          - php

networks:
  furoshiki:
    driver: bridge

